model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/local-model
      # UPDATE THIS TO THE NEW IP: 172.20.0.1
      api_base: "http://172.20.0.1:1234/v1"
      api_key: "lm-studio"

litellm_settings:
  drop_params: true
  set_verbose: true
  json_logs: true
